services:
  app:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - mysql-db
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql-db:3306/propinq
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: password
    networks:
      - springboot-mysql-network

  mysql-db:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: propinq
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - springboot-mysql-network

  mongodb:
    image: mongo:6
    container_name: mongodb
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongo-user
      MONGO_INITDB_ROOT_PASSWORD: secret
      MONGO_INITDB_DATABASE: propinq
    volumes:
      - mongo-data:/data/db
    networks:
      - springboot-mysql-network

volumes:
  mysql-data:
  mongo-data:

networks:
  springboot-mysql-network:
    driver: bridge