services:
  api:
    image: propinq-api:latest
    container_name: propinq-api
    ports:
      - "8080:8080"
      - "35729:35729"
    volumes:
      - ./src:/app/src
      - ./pom.xml:/app/pom.xml
      - maven-cache:/root/.m2
    depends_on:
      - mysql-db
      - mongodb
    environment:
      SPRING_PROFILES_ACTIVE: dev
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql-db:3306/propinq
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: ${DB_PASSWORD}
      SPRING_DATA_MONGODB_URI: mongodb://mongo-user:${MONGODB_PASSWORD}@mongodb:27017/propinq?authSource=admin
    networks:
      - app-network
    stdin_open: true
    tty: true

  frontend:
    image: propinq-frontend:latest
    container_name: propinq-frontend
    ports:
      - "4200:4200"
    networks:
      - app-network

  mysql-db:
    image: mysql:8
    container_name: mysql-db
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD:}
      MYSQL_DATABASE: propinq
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - app-network
    ports:
      - "3306:3306"

  mongodb:
    image: mongo:6
    container_name: mongodb
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongo-user
      MONGO_INITDB_ROOT_PASSWORD: ${MONGODB_PASSWORD}
      MONGO_INITDB_DATABASE: propinq
    volumes:
      - mongo-data:/data/db
    networks:
      - app-network

volumes:
  mysql-data:
  mongo-data:
  maven-cache:

networks:
  app-network:
    driver: bridge