spring:
  application:
    name: propinq
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: ${DDL_AUTO:update}
  datasource:
    url: jdbc:mysql://${MYSQL_HOST:localhost}:${MYSQL_PORT:3306}/propinq
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:password}
    driver-class-name: com.mysql.cj.jdbc.Driver
  data:
    mongodb:
      uri: ${MONGO_URL:mongodb://mongo-user:secret@mongodb:27017/propinq?authSource=admin}
      username: ${MONGO_USER:mongo-user}
      password: ${MONGO_PASSWORD:secret}

springdoc:
  swagger-ui:
    disable-swagger-default-url: true
    path: /

cors:
  allowed-origins: http://localhost:4200