spring:
  devtools:
    restart:
      enabled: true
      poll-interval: 1000
      quiet-period: 400
      additional-paths: src/main
    livereload:
      enabled: true
      port: 35729
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: ${DDL_AUTO:update}
    defer-datasource-initialization: true
    properties:
      hibernate:
        format_sql: true
  datasource:
    url: jdbc:mysql://${MYSQL_HOST}:${MYSQL_PORT:27890}/defaultdb
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  data:
    mongodb:
      uri: mongodb://mongo-user:${MONGODB_PASSWORD:}@mongodb:27017/propinq?authSource=admin
  mail:
    host: ${MAIL_HOST}
    port: ${MAIL_PORT}
    username: ${MAIL_USERNAME:}
    password: ${MAIL_PASSWORD:}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
          timeout: 2000

logging:
  level:
    "[org.springframework.web]": DEBUG
    "[org.hibernate.SQL]": DEBUG
    "[org.hibernate.type.descriptor.sql.BasicBinder]": TRACE

cors:
  allowed-origins: ${CORS_ALLOWED_ORIGINS:http://localhost:4200}

frontend:
  url: ${FRONTEND_URL:http://localhost:4200}

cloudinary:
  cloud-name: ${CLOUD_NAME}
  api-key: ${CLOUD_API_KEY}
  api-secret: ${CLOUD_API_SECRET}

springdoc:
  swagger-ui:
    disable-swagger-default-url: true
    path: /