spring:
  application:
    name: propinq
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: ${DDL_AUTO:create-drop}
  datasource:
    url: jdbc:mysql://${MYSQL_HOST:localhost}:${MYSQL_PORT:3306}/propinq?createDatabaseIfNotExist=true
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:password}
    driver-class-name: com.mysql.cj.jdbc.Driver
  data:
    mongodb:
      uri: ${MONGO_URL:mongodb://mongo-user:secret@mongodb:27017/propinq?authSource=admin}
      username: ${MONGO_USER:mongo-user}
      password: ${MONGO_PASSWORD:secret}
  mail:
    host: ${MAIL_HOST:smtp.gmail.com}
    port: ${MAIL_PORT:587}
    username: ${MAIL_USERNAME:your_email@gmail.com}
    password: ${MAIL_PASSWORD:your_password}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

springdoc:
  swagger-ui:
    disable-swagger-default-url: true
    path: /
frontend:
  url: http://localhost:4200
